spring.application.name=UserService
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:9000
server.port=8081
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:MicroServices}
spring.datasource.username=${DATABASE_USER:myuser}
spring.datasource.password=${DATABASE_PASSWORD:secret}


spring.grpc.client.default-channel.address=localhost:8083
